apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: laravel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: laravel
    spec:
      imagePullSecrets:  # Add this section
      - name: ghcr-secret
      containers:
      - name: nginx
        image: nginx:1.26
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          readOnly: true
          subPath: nginx.conf
      - name: app
        image: ghcr.io/murilolivorato/deploy-laravel-quasar-app/backend:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: laravel-env
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: nginx-config
        configMap:
          name: laravel-nginx