apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        describedObject:
          kind: ingress
          apiVersion: networking.k8s.io/v1
          name: laravel
        target:
          type: AverageValue
          averageValue: 10 # we don't want more than 10rps per replica
        metric:
          name: requests_per_second
